services:
  # API Host Service
  - type: web
    name: uccp-membership-api
    runtime: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./aspnet-core/Dockerfile.api
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: ConnectionStrings__Default
        sync: false
      - key: Redis__Configuration
        value: redis-10168.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:10168,password=yvUTlrTajPq0VXZVjdKwxKhC7rl2Ldok,ssl=False,abortConnect=False
      - key: AuthServer__Authority
        sync: false
      - key: App__CorsOrigins
        value: https://erdzrivera.github.io
      - key: OpenIddict__Applications__Membership_App__RootUrl
        value: https://erdzrivera.github.io/UCCPSBDMembership
      - key: OpenIddict__Applications__Membership_Swagger__RootUrl
        sync: false

  # Auth Server Service
  - type: web
    name: uccp-membership-auth
    runtime: docker
    region: singapore
    plan: free
    branch: main
    dockerfilePath: ./aspnet-core/Dockerfile.auth
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:8080
      - key: ConnectionStrings__Default
        sync: false
      - key: Redis__Configuration
        value: redis-10168.c252.ap-southeast-1-1.ec2.cloud.redislabs.com:10168,password=yvUTlrTajPq0VXZVjdKwxKhC7rl2Ldok,ssl=False,abortConnect=False
      - key: App__SelfUrl
        sync: false
      - key: App__ClientUrl
        value: https://erdzrivera.github.io/UCCPSBDMembership
      - key: App__CorsOrigins
        value: https://erdzrivera.github.io
      - key: App__RedirectAllowedUrls
        value: https://erdzrivera.github.io/UCCPSBDMembership
      - key: AuthServer__Authority
        sync: false
      - key: OpenIddict__Applications__Membership_App__RootUrl
        value: https://erdzrivera.github.io/UCCPSBDMembership
      - key: OpenIddict__Applications__Membership_Swagger__RootUrl
        sync: false
